### ISSUE TITLE
Jenkins signed by unknown authority

### ISSUE THREAD

**Issue by erezo9** [mattermost/mattermost-plugin-jenkins#31]
Hi,
Trying to connect mattermost to jenkins and recieveing:
x509: certificate signed by unknown authority
Is there a way to get pass that?

**Comment by hanzei** [comment]
Is your jenkins server using a self signed certificate?

**Comment by erezo9** [comment]
Yes

**Comment by hanzei** [comment]
Could you please try if loading your self signed certificate into the certificate store of your Mattermost server solves the issue?

**Comment by erezo9** [comment]
Do u have maybe a guide or manual on how to do this?
I have not seen this in there documentation

**Comment by hanzei** [comment]
These steps are depended of your OS. E.g. https://manuals.gfi.com/en/kerio/connect/content/server-configuration/ssl-certificates/adding-trusted-root-certificates-to-the-server-1605.html provides a quick overview.

**Comment by hanzei** [comment]
I'm going to close this as a self signed certificate for the jenkins server is out of scope of this project.
