### ISSUE TITLE
Provide feedback when using an invalid slash command

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-jenkins#37]
When trying to use an invalid command the plugin does not respond or offer any feedback. 
Help should be displayed when using an invalid command

Steps:
- Setup Jenkins and connect
- Type `/jenkins run test2` (run is not a command)

**Observed**: Nothing happens

**Comment by abdulsmapara** [comment]
I would like to fix this issue !
According to me, adding a `default` case to https://github.com/mattermost/mattermost-plugin-jenkins/blob/master/server/command.go#L85 and responding with the message from the `case help` will fix it.

**Comment by abdulsmapara** [comment]
Encountering an error on running `make check-style` (last 3 lines) -
```bash

Running gofmt
go: downloading github.com/waseem18/gojenkins v0.2.1-0.20190413102934-c264e08c78c3
go: downloading github.com/stretchr/testify v1.6.1
go: downloading github.com/hashicorp/go-hclog v0.12.0
go: downloading golang.org/x/sys v0.0.0-20200124204421-9fbb57f87de9
go: downloading google.golang.org/grpc v1.26.0
go: downloading github.com/oklog/run v1.1.0
go: downloading gopkg.in/yaml.v3 v3.0.0-20200313102051-9f266ea9e77c
go: downloading github.com/fatih/color v1.9.0
go: downloading github.com/mattn/go-isatty v0.0.12
go: downloading github.com/mattn/go-colorable v0.1.4
go: downloading google.golang.org/genproto v0.0.0-20200128133413-58ce757ed39b
Checking github.com/mattermost/mattermost-plugin-jenkins/server
Gofmt success
Running govet
env GO111MODULE=off /usr/local/go/bin/go get golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow
/usr/local/go/bin/go vet ./server/...
/usr/local/go/bin/go vet -vettool=/bin/shadow ./server/...
go vet: can't execute /bin/shadow -flags: fork/exec /bin/shadow: no such file or directory
Makefile:58: recipe for target 'govet' failed
make: *** [govet] Error 2

```
However, the tests are successful on `make test` and I am able to bundle the plugin by `make dist`. 
Should I proceed ahead or there is anything that I am doing wrong ?
