### ISSUE TITLE
Include build number in file name when downloading logs

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-jenkins#38]
Now that logs are a files attached to a post that can be downloaded, it would be ideal if the the file name was something like `JobName`-`BuildNumber` instead of just the `JobName`. 
This would make it a bit easier to use when needing to download multiple files

**Comment by hanzei** [comment]
@DHaussermann That should like a reasonable improvement to me. Objections on making this a HW?
